#!/usr/bin/env python
"""
Thin wrapper around the official TIDMAD download_data.py.

Downloads training and validation files using wget commands generated by
the upstream script.  Requires the original TIDMAD repository to be
available either locally or via a git clone.

Usage
-----
    python scripts/download_data.py --output_dir data/ --train_files 2 --validation_files 2

This calls the official script with the same arguments.  If the upstream
script is not present, it is cloned automatically.
"""

from __future__ import annotations

import argparse
import os
import subprocess
import sys
import tempfile


TIDMAD_REPO = "https://github.com/jessicafry/TIDMAD.git"


def find_or_clone_tidmad(work_dir: str) -> str:
    """Return path to the TIDMAD download_data.py script."""
    script_path = os.path.join(work_dir, "TIDMAD", "download_data.py")
    if os.path.isfile(script_path):
        return script_path

    print(f"Cloning TIDMAD repository into {work_dir} …")
    subprocess.run(
        ["git", "clone", "--depth", "1", TIDMAD_REPO],
        cwd=work_dir,
        check=True,
    )
    return script_path


def main() -> None:
    parser = argparse.ArgumentParser(description="Download TIDMAD dataset files.")
    parser.add_argument("--output_dir", "-o", default="data/",
                        help="Destination directory for downloaded files.")
    parser.add_argument("--train_files", "-t", type=int, default=2,
                        help="Number of training files to download (0-20).")
    parser.add_argument("--validation_files", "-v", type=int, default=2,
                        help="Number of validation files to download (0-20).")
    parser.add_argument("--science_files", "-s", type=int, default=0,
                        help="Number of science files to download (0-208).")
    parser.add_argument("--cache", "-c", default="Director",
                        choices=["NY", "NorCal", "SoCal", "Director"],
                        help="OSDF cache location.")
    parser.add_argument("--force", "-f", action="store_true",
                        help="Skip size prompt and proceed directly.")
    parser.add_argument("--skip_downloaded", "-sk", action="store_true",
                        help="Skip already-downloaded files.")
    parser.add_argument("--print", "-p", action="store_true", dest="print_cmds",
                        help="Print wget commands instead of executing them.")
    args = parser.parse_args()

    os.makedirs(args.output_dir, exist_ok=True)

    with tempfile.TemporaryDirectory() as tmpdir:
        script = find_or_clone_tidmad(tmpdir)

        cmd = [
            sys.executable, script,
            "--output_dir", os.path.abspath(args.output_dir),
            "--train_files", str(args.train_files),
            "--validation_files", str(args.validation_files),
            "--science_files", str(args.science_files),
            "--cache", args.cache,
        ]
        if args.force:
            cmd.append("--force")
        if args.skip_downloaded:
            cmd.append("--skip_downloaded")
        if args.print_cmds:
            cmd.append("--print")

        subprocess.run(cmd, check=True)


if __name__ == "__main__":
    main()
